### ISSUE TITLE
Add description and mission statement

### ISSUE THREAD

**Issue by madmas** [friedhof/komunumo-website#3]
It would be nice to see a description and mission statement what his project is about :)

**Comment by McPringle** [comment]
@madmas, can you please check our [updated website](https://www.komunumo.org) if our project description is what you thought of as you raised this issue and is easy to understand?

**Comment by madmas** [comment]
Great! Much better ;-)
A little info on who "we" is and were the project is originating from would be nice, but this is definetly much much better ;-) Thank you

**Comment by McPringle** [comment]
I added an additional sentence about who "we" are with a link to the GitHub organization team.
